In [1]:
%load_ext autoreload
%autoreload 2

import os

os.chdir("../../")

In [3]:
import pandas as pd
from src.evals.transcript import get_clean_transcript
df_aa = pd.read_excel("consolidated_results/ai-director-ai-matcher.xlsx")
df_hh = pd.read_csv("consolidated_results/human-director-human-matcher.csv")
df_ah = pd.read_excel("consolidated_results/ai-director-human-matcher.xlsx")
df_ha = pd.read_excel("consolidated_results/human-director-ai-matcher.xlsx")

transcripts_hh = get_clean_transcript(df_hh, condition="Human-Human", drop_incomplete_rounds=True, add_duration_columns=False)
transcripts_aa = get_clean_transcript(df_aa, condition="AI-AI", drop_incomplete_rounds=True, add_duration_columns=False)
transcripts_ah = get_clean_transcript(df_ah, condition="AI-Human", drop_incomplete_rounds=True, add_duration_columns=False)
transcripts_ha = get_clean_transcript(df_ha, condition="Human-AI", drop_incomplete_rounds=True, add_duration_columns=False)
all_transcripts = pd.concat([transcripts_hh, transcripts_aa, transcripts_ah, transcripts_ha], axis=0).reset_index(drop=True)

all_transcripts.shape, all_transcripts.columns

((344, 5),
 Index(['pair_id', 'condition', 'round_ix', 'accuracy', 'transcript'], dtype='object'))

In [6]:
all_transcripts.to_excel("consolidated_results/all_transcripts_across_4_pair_conditions.xlsx", index=False)

In [7]:
all_transcripts

,pair_id,condition,round_ix,accuracy,transcript
0,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,83.333333,[18:27:25] director: Hi there. The first baske...
1,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,2,91.666667,[18:47:04] director: hi there \n\n[18:47:11] m...
2,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,3,91.666667,[19:05:34] director: hi there \n\n[19:05:41] m...
3,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,4,83.333333,[19:16:36] director: hi there! \n\n[19:16:42] ...
4,3kk7u0fy_2ifxj59u_qhyb02an,Human-Human,1,91.666667,[18:16:40] director: 1 the rabbit facing your ...
...,...,...,...,...,...
339,570521cfde5095001018a0c8,Human-AI,4,58.333333,[20:14:55] director: Round shallow basket with...
340,63614ad9841a7d16ad04512a,Human-AI,1,83.333333,[21:12:09] director: First You have a rabbit w...
341,63614ad9841a7d16ad04512a,Human-AI,2,75.000000,[21:31:30] director: for number 1we have a thi...
342,63614ad9841a7d16ad04512a,Human-AI,3,66.666667,[21:58:55] director: 1 has the tteal with ligh...
343,63614ad9841a7d16ad04512a,Human-AI,4,75.000000,[22:15:34] director: Number 1 is coiled round ...

In [2]:
import pandas as pd

all_and_full_annotated_results_fp = "consolidated_results/all_and_full_annotated_results.csv"
df = pd.read_csv(all_and_full_annotated_results_fp)
df

,pair_id,condition,round_ix,accuracy,transcript,# words,# turns,# utterances,words_per_turn,words_per_utterance,utterances_per_turn,round_duration_seconds,avg_turn_duration_seconds,avg_utterance_duration_seconds,round_duration,avg_turn_duration,avg_utterance_duration,llm_extracted_object_descriptions_GPT_5
0,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,83.333333,[18:27:25] director: Hi there. The first baske...,374,32,33,11.687500,11.333333,1.031250,1123.0,0.562500,35.093750,00:18:43,00:00:00,00:00:35,"{\n ""object_#1"": ""rabbit facing to the righ..."
1,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,2,91.666667,[18:47:04] director: hi there \n\n[18:47:11] m...,352,31,34,11.354839,10.352941,1.096774,1067.0,4.258065,32.333333,00:17:47,00:00:04,00:00:32,"{\n ""object_#1"": ""a rectangle basket, the r..."
2,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,3,91.666667,[19:05:34] director: hi there \n\n[19:05:41] m...,268,26,26,10.307692,10.307692,1.000000,633.0,0.000000,25.320000,00:10:33,00:00:00,00:00:25,"{\n ""object_#1"": ""2 tone basket, dark brown..."
3,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,4,83.333333,[19:16:36] director: hi there! \n\n[19:16:42] ...,299,27,27,11.074074,11.074074,1.000000,807.0,0.000000,31.038462,00:13:27,00:00:00,00:00:31,"{\n ""object_#1"": ""shallow light colored bas..."
4,3kk7u0fy_2ifxj59u_qhyb02an,Human-Human,1,91.666667,[18:16:40] director: 1 the rabbit facing your ...,299,19,38,15.736842,7.868421,2.000000,930.0,23.789474,25.135135,00:15:30,00:00:23,00:00:25,"{\n ""object_#1"": ""the rabbit facing your ri..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,570521cfde5095001018a0c8,Human-AI,4,58.333333,[20:14:55] director: Round shallow basket with...,1090,44,44,24.772727,24.772727,1.000000,904.0,0.000000,21.023256,00:15:04,00:00:00,00:00:21,"{\n ""object_#1"": ""Round shallow basket with..."
340,63614ad9841a7d16ad04512a,Human-AI,1,83.333333,[21:12:09] director: First You have a rabbit w...,1255,42,42,29.880952,29.880952,1.000000,863.0,0.000000,21.048780,00:14:23,00:00:00,00:00:21,"{\n ""object_#1"": ""a rabbit with the fur dow..."
341,63614ad9841a7d16ad04512a,Human-AI,2,75.000000,[21:31:30] director: for number 1we have a thi...,1328,42,43,31.619048,30.883721,1.023810,1433.0,1.547619,34.119048,00:23:53,00:00:01,00:00:34,"{\n ""object_#1"": ""a thick basket with a han..."
342,63614ad9841a7d16ad04512a,Human-AI,3,66.666667,[21:58:55] director: 1 has the tteal with ligh...,1088,38,38,28.631579,28.631579,1.000000,840.0,0.000000,22.702703,00:14:00,00:00:00,00:00:22,"{\n ""object_#1"": ""tteal with lighter bands ..."
343,63614ad9841a7d16ad04512a,Human-AI,4,75.000000,[22:15:34] director: Number 1 is coiled round ...,1070,40,40,26.750000,26.750000,1.000000,934.0,0.000000,23.948718,00:15:34,00:00:00,00:00:23,"{\n ""object_#1"": ""coiled round, with pale h..."

In [3]:
extracted_descriptions_df = pd.read_csv("consolidated_results/aligned_extracted_object_descriptions.csv")
extracted_descriptions_df

,pair_id,condition,round_ix,transcript,object_ix,filename,object_description,clip_score,contrastive_clip_score
0,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,[18:27:25] director: Hi there. The first baske...,1,076.png,rabbit facing to the right,23.387989,-0.898606
1,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,[18:27:25] director: Hi there. The first baske...,2,001.png,"basic round basket, round, has a handle, unifo...",25.962502,1.909953
2,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,[18:27:25] director: Hi there. The first baske...,3,015.png,"rectangle, right side of the lid is propped op...",14.502266,-10.592122
3,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,[18:27:25] director: Hi there. The first baske...,4,009.png,"2 tone white and light brown, the handle comes...",25.246346,1.128692
4,3kk7u0fy_08dnx2dx_ljtwijvs,Human-Human,1,[18:27:25] director: Hi there. The first baske...,5,022.png,"fairly basic, uniform brown color, a braided h...",27.671200,3.773988
...,...,...,...,...,...,...,...,...,...
4123,63614ad9841a7d16ad04512a,Human-AI,4,[22:15:34] director: Number 1 is coiled round ...,8,015.png,"the one with an open lide on one side, closed ...",26.699718,5.751288
4124,63614ad9841a7d16ad04512a,Human-AI,4,[22:15:34] director: Number 1 is coiled round ...,9,033.png,"an animal, with both eyes visible, tiny feet, ...",18.627974,-3.054252
4125,63614ad9841a7d16ad04512a,Human-AI,4,[22:15:34] director: Number 1 is coiled round ...,10,009.png,"the one with the white pattern in the middle, ...",19.910971,-1.654619
4126,63614ad9841a7d16ad04512a,Human-AI,4,[22:15:34] director: Number 1 is coiled round ...,11,017.png,"looks like a deep purse, that's mostly one color",17.102358,-4.718560
4127,63614ad9841a7d16ad04512a,Human-AI,4,[22:15:34] director: Number 1 is coiled round ...,12,040.png,"the burger shaped one, with the dark handle, d...",18.871056,-2.789071

In [4]:
extracted_descriptions_piv = extracted_descriptions_df.pivot(
    index=["pair_id", "condition", "filename",],
    columns="round_ix",
    values="object_description"
)
extracted_descriptions_piv

round_ix                                                                     1  \
pair_id  condition filename
12mwnjm1 AI-AI     001.png   a deep, rounded bucket-style wicker basket, a ...
                   009.png   an oval, boat-shaped basket in pale/whitewashe...
                   012.png   a rectangular tote basket with a single arched...
                   015.png   a rectangular, boxy picnic basket, a tall vert...
                   017.png   a compact handbag-style tan basket with ONE ar...
...                                                                        ...
y5q3cuyo AI-AI     033.png   the round, lidded wicker basket that looks lik...
                   037.png   a tall, cylindrical brown wicker basket (like ...
                   040.png   a squat oval basket with a dark gray-brown bod...
                   065.png   a wide, deep round tub basket, TWO thick side ...
                   076.png   the light tan wicker basket shaped like a duck...

round_ix                                                                     2  \
pair_id  condition filename
12mwnjm1 AI-AI     001.png   deep rounded bucket-shaped wicker basket, VERY...
                   009.png   compact tan handbag/purse-shaped basket, ONE a...
                   012.png   rectangular tote/handbag basket, ONE arched ha...
                   015.png   rectangular, boxy wicker picnic basket, tall u...
                   017.png   open round tub/bucket basket, NO big arched ha...
...                                                                        ...
y5q3cuyo AI-AI     033.png   round, lidded wicker basket, animal/cat face o...
                   037.png   tall, straight-sided cylindrical wicker basket...
                   040.png   squat oval basket that’s two-tone, dark gray/b...
                   065.png   wide, deep ROUND tub basket, TWO thick side ha...
                   076.png   lidded wicker basket shaped like a duck, oval ...

round_ix                                                                     3  \
pair_id  condition filename
12mwnjm1 AI-AI     001.png   deep rounded bucket-style wicker basket, SINGL...
                   009.png   very pale/whitewashed oval “boat-shaped” baske...
                   012.png   a rectangular tote basket, one arched handle, ...
                   015.png   low squat rectangular brown basket, ONE super-...
                   017.png   plain medium-brown wicker “handbag” basket, sq...
...                                                                        ...
y5q3cuyo AI-AI     033.png   round lidded wicker basket, animal/cat face on...
                   037.png   tall, straight-sided cylindrical wicker basket...
                   040.png   squat oval basket that’s two-tone, dark gray/b...
                   065.png   very shallow ROUND tray-basket, single light t...
                   076.png   lidded basket shaped like a duck in profile, o...

round_ix                                                                     4
pair_id  condition filename
12mwnjm1 AI-AI     001.png   a deep rounded bucket-style wicker basket, a S...
                   009.png   the very pale/whitewashed oval “boat-shaped” b...
                   012.png   a rectangular tote basket, ONE arched handle, ...
                   015.png   the rectangular, boxy picnic basket, a tall up...
                   017.png   a compact tan handbag/purse-shaped basket, ONE...
...                                                                        ...
y5q3cuyo AI-AI     033.png   the round, lidded wicker basket, an animal/cat...
                   037.png   a tall, straight-sided cylindrical wicker bask...
                   040.png   a short, wide RECTANGULAR basket with a single...
                   065.png   a wide, deep ROUND tub basket, TWO thick side ...
                   076.png   the lidded basket shaped like a DUCK in profil...

[1032 rows x 4 columns]

In [5]:
extracted_descriptions_piv.columns

Index([1, 2, 3, 4], dtype='int64', name='round_ix')

In [9]:
new_df = extracted_descriptions_piv.reset_index()
new_df

round_ix,pair_id,condition,filename,1,2,3,4
0,12mwnjm1,AI-AI,001.png,"a deep, rounded bucket-style wicker basket, a ...","deep rounded bucket-shaped wicker basket, VERY...","deep rounded bucket-style wicker basket, SINGL...","a deep rounded bucket-style wicker basket, a S..."
1,12mwnjm1,AI-AI,009.png,"an oval, boat-shaped basket in pale/whitewashe...","compact tan handbag/purse-shaped basket, ONE a...",very pale/whitewashed oval “boat-shaped” baske...,the very pale/whitewashed oval “boat-shaped” b...
2,12mwnjm1,AI-AI,012.png,a rectangular tote basket with a single arched...,"rectangular tote/handbag basket, ONE arched ha...","a rectangular tote basket, one arched handle, ...","a rectangular tote basket, ONE arched handle, ..."
3,12mwnjm1,AI-AI,015.png,"a rectangular, boxy picnic basket, a tall vert...","rectangular, boxy wicker picnic basket, tall u...","low squat rectangular brown basket, ONE super-...","the rectangular, boxy picnic basket, a tall up..."
4,12mwnjm1,AI-AI,017.png,a compact handbag-style tan basket with ONE ar...,"open round tub/bucket basket, NO big arched ha...","plain medium-brown wicker “handbag” basket, sq...","a compact tan handbag/purse-shaped basket, ONE..."
...,...,...,...,...,...,...,...
1027,y5q3cuyo,AI-AI,033.png,"the round, lidded wicker basket that looks lik...","round, lidded wicker basket, animal/cat face o...","round lidded wicker basket, animal/cat face on...","the round, lidded wicker basket, an animal/cat..."
1028,y5q3cuyo,AI-AI,037.png,"a tall, cylindrical brown wicker basket (like ...","tall, straight-sided cylindrical wicker basket...","tall, straight-sided cylindrical wicker basket...","a tall, straight-sided cylindrical wicker bask..."
1029,y5q3cuyo,AI-AI,040.png,a squat oval basket with a dark gray-brown bod...,"squat oval basket that’s two-tone, dark gray/b...","squat oval basket that’s two-tone, dark gray/b...","a short, wide RECTANGULAR basket with a single..."
1030,y5q3cuyo,AI-AI,065.png,"a wide, deep round tub basket, TWO thick side ...","wide, deep ROUND tub basket, TWO thick side ha...","very shallow ROUND tray-basket, single light t...","a wide, deep ROUND tub basket, TWO thick side ..."
1031,y5q3cuyo,AI-AI,076.png,the light tan wicker basket shaped like a duck...,"lidded wicker basket shaped like a duck, oval ...","lidded basket shaped like a duck in profile, o...",the lidded basket shaped like a DUCK in profil...

In [27]:
new_df.index.name = "Index"

In [23]:
new_df.to_excel("consolidated_results/entrainment_across_all_transcripts_and_rounds.xlsx", index=False)

In [24]:
new_df

round_ix,pair_id,condition,filename,1,2,3,4
0,12mwnjm1,AI-AI,001.png,"a deep, rounded bucket-style wicker basket, a ...","deep rounded bucket-shaped wicker basket, VERY...","deep rounded bucket-style wicker basket, SINGL...","a deep rounded bucket-style wicker basket, a S..."
1,12mwnjm1,AI-AI,009.png,"an oval, boat-shaped basket in pale/whitewashe...","compact tan handbag/purse-shaped basket, ONE a...",very pale/whitewashed oval “boat-shaped” baske...,the very pale/whitewashed oval “boat-shaped” b...
2,12mwnjm1,AI-AI,012.png,a rectangular tote basket with a single arched...,"rectangular tote/handbag basket, ONE arched ha...","a rectangular tote basket, one arched handle, ...","a rectangular tote basket, ONE arched handle, ..."
3,12mwnjm1,AI-AI,015.png,"a rectangular, boxy picnic basket, a tall vert...","rectangular, boxy wicker picnic basket, tall u...","low squat rectangular brown basket, ONE super-...","the rectangular, boxy picnic basket, a tall up..."
4,12mwnjm1,AI-AI,017.png,a compact handbag-style tan basket with ONE ar...,"open round tub/bucket basket, NO big arched ha...","plain medium-brown wicker “handbag” basket, sq...","a compact tan handbag/purse-shaped basket, ONE..."
...,...,...,...,...,...,...,...
1027,y5q3cuyo,AI-AI,033.png,"the round, lidded wicker basket that looks lik...","round, lidded wicker basket, animal/cat face o...","round lidded wicker basket, animal/cat face on...","the round, lidded wicker basket, an animal/cat..."
1028,y5q3cuyo,AI-AI,037.png,"a tall, cylindrical brown wicker basket (like ...","tall, straight-sided cylindrical wicker basket...","tall, straight-sided cylindrical wicker basket...","a tall, straight-sided cylindrical wicker bask..."
1029,y5q3cuyo,AI-AI,040.png,a squat oval basket with a dark gray-brown bod...,"squat oval basket that’s two-tone, dark gray/b...","squat oval basket that’s two-tone, dark gray/b...","a short, wide RECTANGULAR basket with a single..."
1030,y5q3cuyo,AI-AI,065.png,"a wide, deep round tub basket, TWO thick side ...","wide, deep ROUND tub basket, TWO thick side ha...","very shallow ROUND tray-basket, single light t...","a wide, deep ROUND tub basket, TWO thick side ..."
1031,y5q3cuyo,AI-AI,076.png,the light tan wicker basket shaped like a duck...,"lidded wicker basket shaped like a duck, oval ...","lidded basket shaped like a duck in profile, o...",the lidded basket shaped like a DUCK in profil...

In [29]:
dd = pd.read_excel("consolidated_results/entrainment_across_all_transcripts_and_rounds.xlsx")
dd

,pair_id,condition,filename,1,2,3,4
0,12mwnjm1,AI-AI,001.png,"a deep, rounded bucket-style wicker basket, a ...","deep rounded bucket-shaped wicker basket, VERY...","deep rounded bucket-style wicker basket, SINGL...","a deep rounded bucket-style wicker basket, a S..."
1,12mwnjm1,AI-AI,009.png,"an oval, boat-shaped basket in pale/whitewashe...","compact tan handbag/purse-shaped basket, ONE a...",very pale/whitewashed oval “boat-shaped” baske...,the very pale/whitewashed oval “boat-shaped” b...
2,12mwnjm1,AI-AI,012.png,a rectangular tote basket with a single arched...,"rectangular tote/handbag basket, ONE arched ha...","a rectangular tote basket, one arched handle, ...","a rectangular tote basket, ONE arched handle, ..."
3,12mwnjm1,AI-AI,015.png,"a rectangular, boxy picnic basket, a tall vert...","rectangular, boxy wicker picnic basket, tall u...","low squat rectangular brown basket, ONE super-...","the rectangular, boxy picnic basket, a tall up..."
4,12mwnjm1,AI-AI,017.png,a compact handbag-style tan basket with ONE ar...,"open round tub/bucket basket, NO big arched ha...","plain medium-brown wicker “handbag” basket, sq...","a compact tan handbag/purse-shaped basket, ONE..."
...,...,...,...,...,...,...,...
1027,y5q3cuyo,AI-AI,033.png,"the round, lidded wicker basket that looks lik...","round, lidded wicker basket, animal/cat face o...","round lidded wicker basket, animal/cat face on...","the round, lidded wicker basket, an animal/cat..."
1028,y5q3cuyo,AI-AI,037.png,"a tall, cylindrical brown wicker basket (like ...","tall, straight-sided cylindrical wicker basket...","tall, straight-sided cylindrical wicker basket...","a tall, straight-sided cylindrical wicker bask..."
1029,y5q3cuyo,AI-AI,040.png,a squat oval basket with a dark gray-brown bod...,"squat oval basket that’s two-tone, dark gray/b...","squat oval basket that’s two-tone, dark gray/b...","a short, wide RECTANGULAR basket with a single..."
1030,y5q3cuyo,AI-AI,065.png,"a wide, deep round tub basket, TWO thick side ...","wide, deep ROUND tub basket, TWO thick side ha...","very shallow ROUND tray-basket, single light t...","a wide, deep ROUND tub basket, TWO thick side ..."
1031,y5q3cuyo,AI-AI,076.png,the light tan wicker basket shaped like a duck...,"lidded wicker basket shaped like a duck, oval ...","lidded basket shaped like a duck in profile, o...",the lidded basket shaped like a DUCK in profil...