In [1]:
%load_ext autoreload
%autoreload 2

import os

os.chdir("../../")

In [2]:
import pandas as pd

efficiency_df_annotated = pd.read_json("consolidated_results/efficiency_results_with_red_annotations.json")

In [3]:
efficiency_df_annotated.columns

Index(['pair_id', 'condition', 'round_ix', 'accuracy', 'transcript', '# words',
       '# turns', '# utterances', 'words_per_turn', 'words_per_utterance',
       'utterances_per_turn', 'round_duration_seconds',
       'avg_turn_duration_seconds', 'avg_utterance_duration_seconds',
       'round_duration', 'avg_turn_duration', 'avg_utterance_duration',
       'llm_extracted_object_descriptions_GPT_5', 'extracted_descriptions',
       'red_tokens', 'avg_clip_score', 'avg_contrastive_clip_score', 'Jaccard',
       'Len Reduction Rate', 'Lexical Overlap (Lexical Entrainment)',
       'Rouge-L', 'SBERT Cosim', 'Word Novelty Rate'],
      dtype='object')

### Communication Effort

In [18]:
cols = [
    '# words',
    '# turns', 
    '# utterances', 
    'round_duration_seconds',
]
efficiency_df_annotated[cols].corr("spearman").round(2)

                        # words  # turns  # utterances  round_duration_seconds
# words                    1.00     0.74          0.64                    0.51
# turns                    0.74     1.00          0.96                    0.74
# utterances               0.64     0.96          1.00                    0.75
round_duration_seconds     0.51     0.74          0.75                    1.00

In [25]:
cr_all = efficiency_df_annotated[cols].corr("spearman").round(2).reset_index()
cr_hh = efficiency_df_annotated[efficiency_df_annotated.condition=="Human-Human"][cols].corr("spearman").round(2).reset_index()
cr_all = cr_all[cr_all["index"].isin(["# words", "# turns"])]
cr_hh = cr_hh[cr_hh["index"].isin(["# words", "# turns"])]

In [ ]:
cr_all.insert(0, "Condition", "All Pairs")
cr_hh.insert(0, "Condition", "Human-Human")
combined_cr = pd.concat([cr_all, cr_hh], axis=0).reset_index(drop=True)
combined_cr.T

                                0          1            2            3
Condition               All Pairs  All Pairs  Human-Human  Human-Human
index                     # words    # turns      # words      # turns
# words                       1.0       0.74          1.0         0.73
# turns                      0.74        1.0         0.73          1.0
# utterances                 0.64       0.96         0.75         0.92
round_duration_seconds       0.51       0.74         0.79         0.57

In [28]:
print(combined_cr.to_latex(index=False, float_format="%.2f"))

\begin{tabular}{llrrrr}
\toprule
Condition & index & # words & # turns & # utterances & round_duration_seconds \\
\midrule
All Pairs & # words & 1.00 & 0.74 & 0.64 & 0.51 \\
All Pairs & # turns & 0.74 & 1.00 & 0.96 & 0.74 \\
Human-Human & # words & 1.00 & 0.73 & 0.75 & 0.79 \\
Human-Human & # turns & 0.73 & 1.00 & 0.92 & 0.57 \\
\bottomrule
\end{tabular}

### Lexical Entrainment

In [31]:
efficiency_df_annotated.columns

Index(['pair_id', 'condition', 'round_ix', 'accuracy', 'transcript', '# words',
       '# turns', '# utterances', 'words_per_turn', 'words_per_utterance',
       'utterances_per_turn', 'round_duration_seconds',
       'avg_turn_duration_seconds', 'avg_utterance_duration_seconds',
       'round_duration', 'avg_turn_duration', 'avg_utterance_duration',
       'llm_extracted_object_descriptions_GPT_5', 'extracted_descriptions',
       'red_tokens', 'avg_clip_score', 'avg_contrastive_clip_score', 'Jaccard',
       'Len Reduction Rate', 'Lexical Overlap (Lexical Entrainment)',
       'Rouge-L', 'SBERT Cosim', 'Word Novelty Rate'],
      dtype='object')

In [ ]:
cols = [
    'Lexical Overlap (Lexical Entrainment)',
       'Rouge-L', 'SBERT Cosim', 'Jaccard'
]
cr = efficiency_df_annotated[cols].corr("spearman").round(2).loc[["Lexical Overlap (Lexical Entrainment)"]][[""]]
cr

,Lexical Overlap (Lexical Entrainment),Rouge-L,SBERT Cosim,Jaccard
Lexical Overlap (Lexical Entrainment),1.0,0.89,0.82,0.87

4128