In [1]:
%load_ext autoreload
%autoreload 2

import os

os.chdir("../../")

In [2]:
import pandas as pd

dogs_df = pd.read_excel("baskets_dogs_data/dogs.xlsx")
baskets_df = pd.read_excel("baskets_dogs_data/baskets.xlsx")
pairs = dogs_df.columns.tolist()[3:]
pairs

['Pair_20',
 'Pair_21',
 'Pair_22',
 'Pair_23',
 'Pair_24',
 'Pair_34',
 'Pair_35',
 'Pair_37',
 'Pair_43',
 'Pair_45']

In [4]:
baskets_df.columns

Index(['Round', 'Order', 'TargetObjectIndex', 'Pair_20', 'Pair_21', 'Pair_22',
       'Pair_23', 'Pair_24', 'Pair_34', 'Pair_35', 'Pair_37', 'Pair_43',
       'Pair_45'],
      dtype='object')

In [4]:
from src.data.utils import get_conversations

parsed_transcripts_fp = "baskets_dogs_data/llm_parsed_transcripts.csv"


if os.path.exists(parsed_transcripts_fp):
    transcripts_df = pd.read_csv(parsed_transcripts_fp)
    print("Loaded existing parsed transcripts.")

else:

    transcripts = []

    for object_category in ["baskets", "dogs"]:
        if object_category == "baskets":
            df = baskets_df
        else:
            df = dogs_df
        
        for round_ix in range(1, 5):
            
            for pair in pairs:
                transcript, target_object_indices = get_conversations(
                    df, round_ix, pair, 
                    return_entire_transcript=True
                )
                transcripts.append([object_category, round_ix, pair, transcript])

    transcripts_df = pd.DataFrame(transcripts, 
                                columns=["object_category", "round_ix", "pair_id", "transcript"])
    transcripts_df.to_csv(parsed_transcripts_fp, index=False)
    print("Saved parsed transcripts.")

transcripts_df.shape

Loaded existing parsed transcripts.

(80, 5)

In [10]:
transcripts_df.head()

,object_category,round_ix,pair_id,transcript
0,baskets,1,Pair_20,"D: Alright, the first one is a, uh--is a very ..."
1,baskets,1,Pair_21,"D: Ok, uh…\n You ready?\n \n M: Yup\n \n D: (l..."
2,baskets,1,Pair_22,"D: Alright, hello?\n Um, the first one is--is...."
3,baskets,1,Pair_23,"D: Ok, Parastoo you see the...sort of...oblong..."
4,baskets,1,Pair_24,"D: K, uh, the first basket is longer than the ..."

In [5]:
from string import Template


prompt_tmp = ''' 
You are given a verbatim conversation transcript between two participants \
who are playing a game in which they identify target objects from a set of images.

Your task is to segment the transcript into exactly 10 parts, \
where each part corresponds to a distinct target object discussed in the conversation.

### Requirements

- Each part must be copied verbatim from the transcript.
- Do not paraphrase, summarize, edit, or add any text.
- Each transcript segment must be contiguous (no skipping or reordering lines).
- Every part should focus primarily on one specific target object.
- Do not include explanations, labels, or commentary outside of the transcript text.

### Output Format

Return the result as a valid JSON array of objects. Each object must follow this exact structure:

{
  "part_index": <integer starting from 1>,
  "transcript_segment": "<verbatim transcript segment>"
}

- part_index must range from 1 to 10, in order.
- The final output must be strictly valid JSON and parsable without errors.
- Do not include any text before or after the JSON array.

### Transcript

$transcript

### Your Response

Return only the JSON array described above.
'''

prompt_tmp= Template(prompt_tmp)
print(prompt_tmp.template)

You are given a verbatim conversation transcript between two participants who are playing a game in which they identify target objects from a set of images.

Your task is to segment the transcript into exactly 10 parts, where each part corresponds to a distinct target object discussed in the conversation.

### Requirements

- Each part must be copied verbatim from the transcript.
- Do not paraphrase, summarize, edit, or add any text.
- Each transcript segment must be contiguous (no skipping or reordering lines).
- Every part should focus primarily on one specific target object.
- Do not include explanations, labels, or commentary outside of the transcript text.

### Output Format

Return the result as a valid JSON array of objects. Each object must follow this exact structure:

{
  "part_index": <integer starting from 1>,
  "transcript_segment": "<verbatim transcript segment>"
}

- part_index must range from 1 to 10, in order.
- The final output must be strictly valid JSON and parsable without errors.
- Do not include any text before or after the JSON array.

### Transcript

$transcript

### Your Response

Return only the JSON array described above.

### Test

In [19]:
transcript = transcripts_df.iloc[0].transcript
prompt = prompt_tmp.substitute(transcript=transcript)
print(prompt)

You are given a verbatim conversation transcript between two participants who are playing a game in which they identify target objects from a set of images.

Your task is to segment the transcript into exactly 10 parts, where each part corresponds to a distinct target object discussed in the conversation.

### Requirements

- Each part must be copied verbatim from the transcript.
- Do not paraphrase, summarize, edit, or add any text.
- Each transcript segment must be contiguous (no skipping or reordering lines).
- Every part should focus primarily on one specific target object.
- Do not include explanations, labels, or commentary outside of the transcript text.

### Output Format

Return the result as a valid JSON array of objects. Each object must follow this exact structure:

{
  "part_index": <integer starting from 1>,
  "transcript_segment": "<verbatim transcript segment>"
}

- part_index must range from 1 to 10, in order.
- The final output must be strictly valid JSON and parsable without errors.
- Do not include any text before or after the JSON array.

### Transcript

D: Alright, the first one is a, uh--is a very long basket

 M: Mm-hmm

 D: Uh, it's rectangular in shape
 It's a light tan
 Weaved
 Uh, there's--that's about it, in that, uh--the description of that
 It's uh...I'm facing it with the handle coming over the top

 M: It's right in the middle, the handle?

 D: Yes

 M: Ok

 D: Uh…I don't know, you probably have that one

 M: Yeah *I got it*

D: *We* go with number two here
 Number two's got a huge handle, and it's a very small basket
 It's, uh--got like red, and uh, brown and green weaving in it?
 Huge handle
 Right in the middle, facing towards, uh--I mean I can see right through the handle

 M: Mm-hmm
 It's like a really small, like...

 D: Very tiny basket compared to the handle

 M: Ok
 Alright I think I got that one

D: Ok, number three is a, uh, a large basket, with a, uh, another handle
 It's the same color, but the weave is very wide
 And you got like a lot of spaces in it
 And it looks like, uh...uh, it's black in the bottom, and uh...you can see right through it
 And it's got a--it's got a large--it's got a large handle also, but it's not really that large in proportion to the basket
 It's very circular, the look of the whole thing

 M: Alright, yeah I got that one

D: If you go along the whole thing
 The next one is a very tight weave, without a handle
 It's a very large bowl
 Uh...
 Let's see
 Nothing else...
 Uh, the bottom looks like a solid piece of, I guess, bamboo or whatever they used to h--to mix it together

 M: Mm-hmm

 D: And it's, uh--it's very large, compared to...uh, it's just a large bowl it looks like
 But, uh, it's got a tight weave, and it's all--it's all uniform tan
 It's s--some, some spaces where that look like a darker color, a brown

 M: Alright

 D: But, uh, *that's about it* on that one

 M: *Alright I got that one*
 The next one?

D: The next one is a small basket, with a wide weave, and it's a got a red…weave through the whole thing
 *Uh...*

 M: *Like* a red ribbon?

 D: Yes

 M: Yeah I got that one

 D: Ok

D: The next one is a, uh, a tan bowl that looks very--it looks like solid beading, but it's got some green in it...*on the* other side

 M: *Alright I got that*
 Next one

D: Ok, the next one has a lid on it
 Two handles on the sides

 M: Mm-hmm

 D: Uh, the lid is on top of it and the handles come through the lid
 Uh, it's got a--it's a...tan with a little--like a little knob on the lid itself

 M: Ok, yeah I see this one

D: Alright
 The next one is uh--is triangular

 M: I got it

 D: Ok

 (laughter)

D: The next one is...uh...got a squarish handle, with a li--with a, uh, a round lid, and it looks similar to uh, you know, the old style picnic baskets

 M: And it's kinda like a...a circle though?

 D: Yes, *circular, it is* circular

 M: *Alright, I got it*

D: That's the difference
 And the last one that I have has a similar handle to the previous one--

 M: Mm-hmm

 D: --but it has a, uh--it looks like a very rough looking round lid, but it it--it itself is, uh, more squared
 Almost a little rectangular
 Tapers towards the bottom

 M: Alright I got that one

 D: Alright

### Your Response

Return only the JSON array described above.

In [20]:
from src.llms.openai import get_response

_, response = get_response(
    prompt,
    model_name="gpt-5-nano"
)
print(response)

[
  {
    "part_index": 1,
    "transcript_segment": "D: Alright, the first one is a, uh--is a very long basket\n \n M: Mm-hmm\n \n D: Uh, it's rectangular in shape\n It's a light tan\n Weaved\n Uh, there's--that's about it, in that, uh--the description of that\n It's uh...I'm facing it with the handle coming over the top\n \n M: It's right in the middle, the handle?\n \n D: Yes\n \n M: Ok\n \n D: Uh…I don't know, you probably have that one\n \n M: Yeah *I got it*"
  },
  {
    "part_index": 2,
    "transcript_segment": "D: *We* go with number two here\n Number two's got a huge handle, and it's a very small basket\n It's, uh--got like red, and uh, brown and green weaving in it?\n Huge handle\n Right in the middle, facing towards, uh--I mean I can see right through the handle\n \n M: Mm-hmm\n It's like a really small, like...\n \n D: Very tiny basket compared to the handle\n \n M: Ok\n Alright I think I got that one"
  },
  {
    "part_index": 3,
    "transcript_segment": "D: Ok, number three is a, uh, a large basket, with a, uh, another handle\n It's the same color, but the weave is very wide\n And you got like a lot of spaces in it\n And it looks like, uh...uh, it's black in the bottom, and uh...you can see right through it\n And it's got a--it's got a large--it's got a large handle also, but it's not really that large in proportion to the basket\n It's very circular, the look of the whole thing\n \n M:Alright, yeah I got that one"
  },
  {
    "part_index": 4,
    "transcript_segment": "D: If you go along the whole thing\n The next one is a very tight weave, without a handle\n It's a very large bowl\n Uh...\n Let's see\n Nothing else...\n Uh, the bottom looks like a solid piece of, I guess, bamboo or whatever they used to h--to mix it together\n \n M: Mm-hmm\n \n D: And it's, uh--it's very large, compared to...uh, it's just a large bowl it looks like\n But, uh, it's got a tight weave, and it's all--it's all uniform tan\n It's s--some, some spaces where that look like a darker color, a brown\n \n M: Alright\n \n D: But, uh, *that's about it* on that one\n \n M: *Alright I got that one*\n The next one?"
  },
  {
    "part_index": 5,
    "transcript_segment": "D: The next one is a small basket, with a wide weave, and it's a got a red…weave through the whole thing\n *Uh...*\n \n M: *Like* a red ribbon?\n \n D: Yes\n \n M: Yeah I got that one\n \n D: Ok"
  },
  {
    "part_index": 6,
    "transcript_segment": "D: The next one is a, uh, a tan bowl that looks very--it looks like solid beading, but it's got some green in it...*on the* other side\n \n M: *Alright I got that*\n Next one"
  },
  {
    "part_index": 7,
    "transcript_segment": "D: Ok, the next one has a lid on it\n Two handles on the sides\n \n M: Mm-hmm\n \n D: Uh, the lid is on top of it and the handles come through the lid\n Uh, it's got a--it's a...tan with a little--like a little knob on the lid itself\n \n M: Ok, yeah I see this one\n \nD:Alright"
  },
  {
    "part_index": 8,
    "transcript_segment": "D: The next one is uh--is triangular\n \n M: I got it\n \n D: Ok\n \n (laughter)"
  },
  {
    "part_index": 9,
    "transcript_segment": "D: The next one is...uh...got a squarish handle, with a li--with a, uh, a round lid, and it looks similar to uh, you know, the old style picnic baskets\n \n M: And it's kinda like a...a circle though?\n \n D: Yes, *circular, it is* circular\n \n M: *Alright, I got it*\n\nD: That's the difference"
  },
  {
    "part_index": 10,
    "transcript_segment": " And the last one that I have has a similar handle to the previous one--\n \n M: Mm-hmm\n \n D: --but it has a, uh--it looks like a very rough looking round lid, but it it--it itself is, uh, more squared\n Almost a little rectangular\n Tapers towards the bottom\n \n M: Alright I got that one\n \n D: Alright"
  }
]

### Deployment

In [ ]:
from tqdm import tqdm

parsed_transcripts_fp = "baskets_dogs_data/llm_parsed_transcripts.csv"

for ix, row in tqdm(transcripts_df.iterrows(), total=len(transcripts_df)):
    transcript = row.transcript
    prompt = prompt_tmp.substitute(transcript=transcript)

    if not pd.isna(row.get("model_response")):
        print(f"Skipping index {ix} as it already has a response.")
        continue

    _, response = get_response(
        prompt,
        model_name="gpt-5-nano"
    )
    transcripts_df.at[ix, "model_response"] = response
    transcripts_df.to_csv(parsed_transcripts_fp, index=False)

  0%|          | 0/80 [00:00<?, ?it/s]

100%|██████████| 80/80 [2:22:28<00:00, 106.85s/it]

In [35]:
import re
import json


def parse_llm_response(response):
    response = response.replace("json", "").strip()
    try:
        parsed = json.loads(response)
    except json.JSONDecodeError as e:
        print(f"JSONDecodeError: {e}")
        parsed = []
    return parsed

# def parse_llm_response(response):
#     responses = re.findall(r"\{[^\}]+\}", response)
#     outputs = []
#     if not responses:
#         return outputs
    
#     for response in responses:
    
#         try:
#             parsed = json.loads(response)
            
#         except json.JSONDecodeError:
#             parsed = {}
        
#         outputs.extend(parsed)

#     return outputs

In [36]:
transcripts_df["parsed_response"] = transcripts_df["model_response"].apply(parse_llm_response)
transcripts_df.head()

JSONDecodeError: Invalid control character at: line 4 column 42 (char 68)

,object_category,round_ix,pair_id,transcript,model_response,parsed_response
0,baskets,1,Pair_20,"D: Alright, the first one is a, uh--is a very ...","[\n {\n ""part_index"": 1,\n ""transcript_...","[{'part_index': 1, 'transcript_segment': 'D: A..."
1,baskets,1,Pair_21,"D: Ok, uh…\n You ready?\n \n M: Yup\n \n D: (l...","[\n {\n ""part_index"": 1,\n ""transcript_...","[{'part_index': 1, 'transcript_segment': 'D: O..."
2,baskets,1,Pair_22,"D: Alright, hello?\n Um, the first one is--is....","[\n {\n ""part_index"": 1,\n ""transcript_...","[{'part_index': 1, 'transcript_segment': 'D: A..."
3,baskets,1,Pair_23,"D: Ok, Parastoo you see the...sort of...oblong...","[\n {\n ""part_index"": 1,\n ""transcript_...","[{'part_index': 1, 'transcript_segment': 'D: O..."
4,baskets,1,Pair_24,"D: K, uh, the first basket is longer than the ...","[\n {\n ""part_index"": 1,\n ""transcript_...","[{'part_index': 1, 'transcript_segment': 'D: K..."

In [33]:
sub = transcripts_df[transcripts_df.parsed_response.apply(len) != 10]
sub

,object_category,round_ix,pair_id,transcript,model_response,parsed_response
43,dogs,1,Pair_23,"D: Ok (laughs)\nOk, this dog is standing upri...","[\n {\n ""part_index"": 1,\n ""transcript_...",[]

In [34]:
print(sub.model_response.iloc[0])

[
  {
    "part_index": 1,
    "transcript_segment": "D: Ok (laughs)
Ok, this dog is standing upright
(laughs)

M: Ok

D: Um, he's got a patch of black around his stomach and back area, and his legs are more like a camel color

M: Um, like a orangish color?

D: Yeah

M: Um, like towards his tail, is it like a y--uh--yellowish…color?

D: Yeah, but he has like a black tip on his tail

M: Yup got it, ok"
  },
  {
    "part_index": 2,
    "transcript_segment": "D: Ok, number two--he's--
(cell phone rings)
He's furry
M: He's furry
Ok

D: Um, (cell phone rings) and he's--his legs--he's--he's sort of like turning towards his butt

M: (laughs)
Ok

D: And, um, he's got white legs, and his--he's got a patch of black on his--his--his butt, too

M: He's got white legs, you said?

D: Yeah, like he looks like he's got maybe like, a little bit of fur
Like maybe two inches of fur, that’s it

M: White legs
Does he look like a wolf?
Kinda?

D: N--no
He's looking--um, the way he's facing, *he--*

M: *He's* facing--mm--like he's looking at his **his tail?**

D: **His left**
Yeah, he's looking at his tail, ***sort of***

M:  ***Is*** there like a little--like greenish outline on him?

D: No, that’s not the one

M: That’s not the one, ok

D: No, the--the one that you're talking about I think is sitting
The one I’m talking about is standing

M:  Ok, um, does he have like a black outline, and a yellow on the bottom?

D:  Yeah

M:  Ok, go ahead

M:  Ok, go ahead"
  },
  {
    "part_index": 3,
    "transcript_segment": "D:  Ok, number three is the one--he's sitting down
M:  Mm-hmm
D:  He's got a brown collar on him…and he's surrounded by green
M:  Uh, he's looking back at his tail
D:  Yeah
M:  Ok, go ahead"
  },
  {
    "part_index": 4,
    "transcript_segment": "D: Number four is the really short dog
He looks like a weiner
M: (laughs)
*Ok*
**Ok, I got him**

D: *He's* got really stubby legs, and **he's all black**"
  },
  {
    "part_index": 5,
    "transcript_segment": "D: Number five is like the poodle dog?
He's all black, and he's got the shiny collar thing that you can only see

M: Like a circular-- *like* sil--silver color

D: *Yeah*

M:  Ok, go ahead"
  },
  {
    "part_index": 6,
    "transcript_segment": "D:  Number six looks like a Doberman
It's like shiny black
Outlined *in* green

M:  *Oh*
Right, ok

D:  Ok, number seven is--he looks like a cocker spaniel
He's got like longish hair, and he's looking up as *if--*

M:  *Ok,* and the gru--and the grass around him

D:  Yeah

M:  Ok"
  },
  {
    "part_index": 7,
    "transcript_segment": "D:  Number eight (laughs) looks like a bulldog
He--his legs look like he's digging into the ground and *he's--*

M:  *Ok* and he has like a…

D:  Like a puppy fa--like a sad face

M:  Ok, go ahead"
  },
  {
    "part_index": 8,
    "transcript_segment": "D:  Number nine is like the wolf dog

M:  Um, white tail

D:  Yeah

M:  Ok"
  },
  {
    "part_index": 9,
    "transcript_segment": "D:  And number ten is the short one
He looks like he has a beard

M:  Uh…

D:  And his tail is pointing up

M:  Wait a minute, uh--
Has he got like long, brown hair?

D:  Mmm…
Mmm…no

M:  No

D:  He's all black

M:  He's all black?

D:  Yeah

M:  Oh ok
Ok, you're gonna have to go back to number *seven*

D:  *Seven*?

M:  Mm-hmm

D:  Yeah
Number seven--he has--his ears **are droopy, not high**"
  },
  {
    "part_index": 10,
    "transcript_segment": "**(cell phone rings)**

M:  And he's got brown fur?

D:  Yeah

M:  And, it's like *a…greenish background?*

*(cell phone rings)*

D:  Yeah

M:  Ok"
  }
]

In [29]:
# print(transcripts_df.iloc[1].model_response)

In [30]:
print(json.dumps(transcripts_df.iloc[1].parsed_response, indent=4))

[
    {
        "part_index": 1,
        "transcript_segment": "D: Ok, uh\u2026\n You ready?\n \n M: Yup\n \n D: (laughs)\n Ok, the first one is a long basket\n It looks like a rectangle\n It's probably the longest one in the picture\n It's square in shape\n Rectangular in shape\n \n M: Ok\n \n D: You got it?\n \n M: Yup"
    },
    {
        "part_index": 2,
        "transcript_segment": "D: Ok\n The second one has a very big handle on it, and a very small basket in a pyramidal shape\n And a really big, circular looking handle\n \n M: Big circular looking handle\n Alright\n \n D: Big circular handle\n It's probably got the longest base from the basket to the hang--uh, handle\n \n M: Ok"
    },
    {
        "part_index": 3,
        "transcript_segment": "D: Uh, third one has, uh, criss-crossing--oh, they all have criss-crossing weaves, but this one has probably the one with the most open space in between each\n \n M: Alright\n Got it\n \n D: And it's got a circular handle\n \n M: Alright I got it"
    },
    {
        "part_index": 4,
        "transcript_segment": "D: Uh, the fourth one is one of the biggest, uh, baskets in the picture\n It's really, uh, stitched closely\n Like, the crossing is really close\n \n M: Ok\n \n D: And it's oval shaped\n Round shaped\n \n M: Ok, does it have handles on it?\n \n D: No handles\n \n M: No handles\n \n D: Very *circular*\n \n M: *Did* number one have handles on each end?\n \n D: Y--uh, no\n One--number one had a--one handle in the middle\n \n M: Ok\n This one has no handles at all?\n \n D: No handles at all\n \n M: Alright I got it\n \n D: And it's very big, like eh deep\n \n M: Ok\n *Go to five*"
    },
    {
        "part_index": 5,
        "transcript_segment": "D: *Ok*\n Five is got a red ribbon around it\n \n M: Ok, go ahead\n Six"
    },
    {
        "part_index": 6,
        "transcript_segment": "D: Six has a green lining in the back\n \n M: Ok, go ahead"
    },
    {
        "part_index": 7,
        "transcript_segment": "D: Seven has a han--uh, a cover on it, with, uh, two handles on the side?\n \n M: Uh...\n *K*, go ahead\n \n D: Is it *golden*?\n \n M: Yeah, I got it"
    },
    {
        "part_index": 8,
        "transcript_segment": "D: Eight is uh...a heart shape purse looking thing\n \n M: Alright, go ahead"
    },
    {
        "part_index": 9,
        "transcript_segment": "D: Number nine is a round, uh, bucket with a cover and a squarish handle on it\n \n M: Ok"
    },
    {
        "part_index": 10,
        "transcript_segment": "And number ten is, uh, the only one left I guess\n Is the...\n \n M: Oh I have four left, so I guess, *um...*\n \n D: *It's long*\n Yeah\n \n M: It's long?\n \n D: **Yeah, it**--I mean, you know\n ***Uh, vertical***\n \n M: **Does it--**\n ***Is it... two handles*** on the side?\n \n D: No two handles on the side\n Just one handle\n \n M: One handle and it's long\u2026\n Hmm\n \n D: It's got a cover and one handle\n \n M: Cover and one handle\n \n D: And it's really uh, bi--like deep\n \n M: Ok\n Ok I got it"
    }
]